#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}
- {name: 'Project Four',  url: 'proj-4'}
- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {name: 'Twitter',   link: 'https://twitter.com/'}
- {name: 'Instagram', link: 'https://instagram.com/'}
- {name: 'Github',    link: 'https://github.com/'}
- {name: 'Linkedin',  link: 'https://linkedin.com/in/'}
- {name: 'Envelope',  link: 'mailto:mailto:youremail@example.com'}